CREATE TABLE `tickets` (
  `ticket_id` bigint NOT NULL,
  `ticket_type` varchar(100) DEFAULT NULL,
  `channel` varchar(50) DEFAULT NULL,
  `priority` enum('Low','Medium','High','Critical') NOT NULL,
  `status` enum('Open','In Progress','Pending','Closed') NOT NULL,
  `first_response_at` datetime DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `handling_hours_after_first_response` decimal(10,2) DEFAULT NULL,
  `sla_target_hours` decimal(10,2) DEFAULT NULL,
  `sla_breached` tinyint(1) NOT NULL DEFAULT '0',
  `satisfaction` tinyint DEFAULT NULL,
  `product` varchar(120) DEFAULT NULL,
  `purchase_date` datetime DEFAULT NULL,
  `ticket_subject` varchar(255) DEFAULT NULL,
  `ticket_description` text,
  `resolution_text` text,
  PRIMARY KEY (`ticket_id`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_first_resp` (`first_response_at`),
  KEY `idx_resolved` (`resolved_at`),
  CONSTRAINT `tickets_chk_1` CHECK ((`priority` in (_utf8mb4'Low',_utf8mb4'Medium',_utf8mb4'High',_utf8mb4'Critical'))),
  CONSTRAINT `tickets_chk_2` CHECK ((`status` in (_utf8mb4'Open',_utf8mb4'In Progress',_utf8mb4'Pending',_utf8mb4'Closed'))),
  CONSTRAINT `tickets_chk_3` CHECK (((`status` <> _utf8mb4'Closed') or (`resolved_at` is not null)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
